"""
synthesizer.py — Final report generation.

Workspace-first. Accepts a `Workspace` (preferred) or a legacy `SchemaInfo`
plus condensed `AnalysisMemory`, and produces markdown or HTML reports
optionally enriched with web research findings and mutation summaries.
"""

from __future__ import annotations
import time
from pathlib import Path
from typing import TYPE_CHECKING

from llm    import call_chat
from memory import AnalysisMemory
from utils  import get_logger

if TYPE_CHECKING:
    from core   import Workspace
    from schema import SchemaInfo

log = get_logger("synthesizer")

_REPORTS_DIR = Path("output") / "reports"


# ---------------------------------------------------------------------------
# LLM prompts
# ---------------------------------------------------------------------------

_SYSTEM = """\
You are a professional data analyst writing a structured report.
Write clear, concise markdown. Reference specific numbers from the analysis.
Do not invent data that is not present in the provided results.\
"""

_USER_TEMPLATE = """\
{workspace_block}

ORIGINAL REQUEST
"{query}"

ANALYSIS RESULTS  ({n_steps} steps, {n_ok} succeeded)
{memory_context}

{web_section}{mutation_section}CHARTS GENERATED
{chart_list}

Write a professional markdown report:
# [Descriptive Title]

## Executive Summary
(3–5 sentences — cite specific numbers and named workspace objects)

## Findings
(One ## section per successful analysis step — use the step description as heading)

## Key Insights
(3–6 bullets — specific numbers only, no generalities)

## Recommendations
(2–4 actionable bullets)

{web_instructions}{mutation_instructions}Rules:
- Reference only numbers present in the results above.
- Refer to objects by their workspace names (spreadsheets, documents, tables).
- Skip failed steps silently.
- Keep under 900 words.
- No markdown fences around the output.\
"""

_WEB_SECTION_TEMPLATE   = "WEB RESEARCH CONTEXT\n{web_context}\n\n"
_WEB_INSTRUCTIONS       = "- Include a \"## External Context\" section summarising the web findings.\n"
_MUTATION_SECTION_TEMPLATE = "MUTATIONS APPLIED\n{mutation_context}\n\n"
_MUTATION_INSTRUCTIONS  = "- Include a \"## Data Updates\" section listing the mutations made.\n"


# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 960px; margin: 40px auto; padding: 0 20px;
         color: #1a1a1a; background: #fafafa; }}
  h1   {{ color: #1a1a2e; border-bottom: 2px solid #4C72B0; padding-bottom: 8px; }}
  h2   {{ color: #2d3561; margin-top: 32px; }}
  h3   {{ color: #4C72B0; }}
  ul   {{ line-height: 1.8; }}
  li   {{ margin-bottom: 4px; }}
  pre  {{ background: #f0f0f0; padding: 12px; border-radius: 6px;
         overflow-x: auto; font-size: 13px; }}
  code {{ background: #f0f0f0; padding: 2px 5px; border-radius: 3px; }}
  .meta {{ color: #666; font-size: 13px; margin-bottom: 24px; }}
  .chart-img {{ max-width: 100%; border: 1px solid #ddd;
                border-radius: 6px; margin: 12px 0; }}
  .badge {{ background: #4C72B0; color: white; padding: 2px 8px;
            border-radius: 10px; font-size: 12px; }}
</style>
</head>
<body>
{body}
<div class="meta">Generated by AI Workspace Agent &nbsp;|&nbsp; {timestamp}</div>
</body>
</html>\
"""


def _markdown_to_html_body(md: str, chart_paths: list[str]) -> str:
    """Lightweight md → HTML conversion (no extra libraries)."""
    import re
    lines  = md.splitlines()
    html   = []
    in_ul  = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("### "):
            if in_ul:
                html.append("</ul>"); in_ul = False
            html.append(f"<h3>{stripped[4:]}</h3>")
        elif stripped.startswith("## "):
            if in_ul:
                html.append("</ul>"); in_ul = False
            html.append(f"<h2>{stripped[3:]}</h2>")
        elif stripped.startswith("# "):
            if in_ul:
                html.append("</ul>"); in_ul = False
            html.append(f"<h1>{stripped[2:]}</h1>")
        elif stripped.startswith("- ") or stripped.startswith("* "):
            if not in_ul:
                html.append("<ul>"); in_ul = True
            item = stripped[2:]
            item = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", item)
            item = re.sub(r"`(.+?)`", r"<code>\1</code>", item)
            html.append(f"<li>{item}</li>")
        elif stripped == "":
            if in_ul:
                html.append("</ul>"); in_ul = False
            html.append("")
        else:
            if in_ul:
                html.append("</ul>"); in_ul = False
            line2 = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", stripped)
            line2 = re.sub(r"`(.+?)`", r"<code>\1</code>", line2)
            html.append(f"<p>{line2}</p>")
    if in_ul:
        html.append("</ul>")
    if chart_paths:
        html.append("<h2>Charts</h2>")
        for p in chart_paths:
            rel = Path(p).as_posix()
            html.append(f'<img class="chart-img" src="{rel}" alt="chart">')
    return "\n".join(html)


def _md_title(report: str) -> str:
    for line in report.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return "Workspace Report"


# ---------------------------------------------------------------------------
# Workspace summary block (preferred input)
# ---------------------------------------------------------------------------

def _workspace_block_from_workspace(workspace: "Workspace") -> str:
    from core import compile_context  # noqa: PLC0415
    return compile_context(workspace, include_memory=False)


def _workspace_block_from_schema(schema: "SchemaInfo") -> str:
    # Back-compat shim for callers that pass only a schema.
    return (
        "=== WORKSPACE ===\n"
        f"Spreadsheets (1):\n"
        f"  {Path(schema.file_path).name}  [{schema.shape[0]}×{schema.shape[1]}]"
        f"  cols: {', '.join(schema.columns[:8])}{'…' if len(schema.columns) > 8 else ''}"
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def synthesize_report(
    query:         str,
    schema:        "SchemaInfo | None"   = None,
    memory:        AnalysisMemory | None = None,
    *,
    workspace:     "Workspace | None"    = None,
    stream:        bool                  = False,
    output_format: str                   = "markdown",
    save_to_disk:  bool                  = True,
) -> str:
    """
    Build a report from accumulated AnalysisMemory.

    Pass either `workspace` (preferred) or `schema` (legacy). Returns markdown
    by default; pass output_format="html" for the full styled HTML document.
    """
    if memory is None:
        raise ValueError("synthesize_report: memory is required")
    if workspace is None and schema is None:
        raise ValueError("synthesize_report: pass workspace= or schema=")

    workspace_block = (
        _workspace_block_from_workspace(workspace)
        if workspace is not None
        else _workspace_block_from_schema(schema)  # type: ignore[arg-type]
    )

    n_steps = len(memory.results)
    n_ok    = memory.success_count
    memory_ctx = memory.to_context(max_chars_per_step=600)

    # Web findings
    web_section = web_instructions = ""
    if memory.web_findings:
        ctx = "\n\n".join(w.context_line(400) for w in memory.web_findings)
        web_section      = _WEB_SECTION_TEMPLATE.format(web_context=ctx)
        web_instructions = _WEB_INSTRUCTIONS

    # Mutations — pull from both AnalysisMemory.excel_updates and the workspace
    mutation_lines: list[str] = []
    for u in memory.excel_updates:
        line = f"  - {u.action}: column '{u.column}' ({u.rows_affected} rows)"
        if u.detail:
            line += f" — {u.detail}"
        mutation_lines.append(line)
    if workspace is not None:
        for m in workspace.memory.recent_mutations(10):
            if not m.success:
                continue
            line = f"  - {m.action} on {m.object_kind}:{m.object_name}"
            if m.detail:
                line += f" — {m.detail}"
            mutation_lines.append(line)

    mutation_section = mutation_instructions = ""
    if mutation_lines:
        # Dedupe while preserving order
        seen: set[str] = set()
        dedup: list[str] = []
        for ln in mutation_lines:
            if ln not in seen:
                dedup.append(ln); seen.add(ln)
        mutation_section      = _MUTATION_SECTION_TEMPLATE.format(mutation_context="\n".join(dedup))
        mutation_instructions = _MUTATION_INSTRUCTIONS

    chart_list = (
        "\n".join(f"  - {p}" for p in memory.chart_paths)
        if memory.chart_paths else "  (none)"
    )

    messages = [
        {"role": "system", "content": _SYSTEM},
        {"role": "user",   "content": _USER_TEMPLATE.format(
            workspace_block=workspace_block,
            query=query,
            n_steps=n_steps,
            n_ok=n_ok,
            memory_context=memory_ctx,
            web_section=web_section,
            web_instructions=web_instructions,
            mutation_section=mutation_section,
            mutation_instructions=mutation_instructions,
            chart_list=chart_list,
        )},
    ]

    log.debug("synthesizer: n_steps=%d ok=%d prompt_len=%d",
              n_steps, n_ok, sum(len(m["content"]) for m in messages))

    t0 = time.perf_counter()
    if stream:
        print("\n  Synthesizing report …\n  ", end="", flush=True)

    md_report = call_chat(messages, stream_to_stdout=stream).strip()
    elapsed   = time.perf_counter() - t0
    log.debug("synthesizer: %d chars in %.1fs", len(md_report), elapsed)

    if save_to_disk:
        _save_report(md_report, memory.chart_paths, output_format)

    if output_format == "html":
        return _to_html(md_report, memory.chart_paths)
    return md_report


def _to_html(md: str, chart_paths: list[str]) -> str:
    from datetime import datetime
    title = _md_title(md)
    body  = _markdown_to_html_body(md, chart_paths)
    return _HTML_TEMPLATE.format(
        title=title,
        body=body,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )


def _save_report(md: str, chart_paths: list[str], fmt: str) -> None:
    from datetime import datetime
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    ts   = datetime.now().strftime("%Y%m%d_%H%M%S")
    md_path = _REPORTS_DIR / f"report_{ts}.md"
    md_path.write_text(md, encoding="utf-8")
    log.debug("synthesizer: saved %s", md_path)
    if fmt == "html":
        html_path = _REPORTS_DIR / f"report_{ts}.html"
        html_path.write_text(_to_html(md, chart_paths), encoding="utf-8")
        log.debug("synthesizer: saved %s", html_path)
